# Generated by Django 4.2.3 on 2023-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(unique=True)),
                ('done', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
